### ISSUE TITLE
What technology/concept/idea has you the most intrigued excited?

### ISSUE THREAD

**Issue by mattzaitley** [Rchristiani/ama#1]
What new tech/concept/tool/idea are you most excited about and think has tons of potential?

**Comment by Rchristiani** [comment]
I have been going really in-depth into JS the last 2 years. So I am really excited about the various frameworks and libraries.

I have been spending a lot of time with Ember lately and I really like it. It is a lot to get into, but when you do it is great. I have also been doing a lot of research and reading it ES6(ES2015), and ember-cli has babel build in so it is great!
