### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [Rchristiani/ama#2]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by Rchristiani** [comment]
![screenshot_2015-07-10-14-38-47](https://cloud.githubusercontent.com/assets/1775147/8626318/3e34d826-2712-11e5-9d4d-093017d87d90.png)

My screen is pretty simple. I like to keep the things I use most on there. I say that, but I have only really used Aribnb a few times to set up a trip to Vancouver in September. The bottom row is the most frequently used!

**Comment by drewminns** [comment]
Dominos :tada:

**Comment by sindresorhus** [comment]
@Rchristiani Fyi, you close the issue when you've answered it ;)

**Comment by Rchristiani** [comment]
Right! Thanks.
