### ISSUE TITLE
What's your favorite new ES2015 feature and why?

### ISSUE THREAD

**Issue by sindresorhus** [Rchristiani/ama#3]

**Comment by Rchristiani** [comment]
I think my favourite feature from ES2015 are the Arrow functions. 

They are simple but powerful. I have been thinking about how to teach ES2015 lately and thinking about the "Easy Wins" that I can start to introduce. Arrow functions to me seems like an easy concept that some can get into. There are so many other features, some simpler, some more complex, but arrows are my favourite.
