### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by sindresorhus** [Rchristiani/ama#5]

**Comment by Rchristiani** [comment]
Whoa, I didn't see this one. Late!

One of my favourite projects on Github is my [JS Frameworks](https://github.com/Rchristiani/js-frameworks) project. It is very simple, but it has helped quite a few students understand how some of the frameworks they have heard about work. It is in no way a ground breaking repo, but I get a lot of satisfaction when I hear that I have helped even one or two people.
