### ISSUE TITLE
What do you think about Spain?

### ISSUE THREAD

**Issue by aarroyoc** [Rchristiani/ama#8]
How do people from outside Spain thinks about Spain? and How do you think about Spain?

**Comment by Rchristiani** [comment]
I like Spain!

I was just in Barcelona last October and it was amazing. I love traveling to Europe and seeing these cities that have so much culture and history to them. I am from Toronto, Canada. We have some history and culture, nothing like Spain. 

After coming home I looked at jobs for studios in Spain! It is nice to dream some times!

I can't wait to go back sometime soon!
