### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [Rchristiani/ama#9]

**Comment by Rchristiani** [comment]
Hi! Sorry for the late reply!

I do participate in mentoring and coaching! In my job as an instructor at HackerYou, we end of mentoring and coaching a lot of junior developers. These are developer still in the current bootcamp, or developers and that have graduated and are out in the world working. Everyone has different situations and sometime the environments the are hired at do not provide any sort of mentorship!

I think it is really important to take the time to help people if they ask you questions or need guidance, I have not been in the industry long, only about 6 or 7 years, but any sort of guidance you can offer to someone can be really helpful!
